services:
  - type: web
    name: event-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        fromGroup: mongodb-creds  # Move secrets to Render's Environment Groups
      - key: PORT
        value: 10000  # Required for Render
      - key: NODE_ENV
        value: production