services:
  - type: web
    name: event-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jeronorhodah:M03310@m0.axwbnlk.mongodb.net/?retryWrites=true&w=majority&appName=M0
