services:
  - type: web
    name: event-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://<username>:<password>@cluster.mongodb.net/eventDB